#!/usr/bin/env python

import sys, os, pwd
import platform

user = pwd.getpwuid(os.getuid())[0]
if user != 'root':
    print("login as root and run again")
    sys.exit()

py_vers = platform.python_version().split(".")
print(py_vers)

#os.system('dnf -y install emacs')
os.system('rm -rf tmp; mkdir tmp; cd tmp; git clone http://github.com/yliow/update-vm-data')

# latex
os.system('rm -rf /usr/share/texlive/texmf-local/tex/latex/yliowtest')
os.system('mkdir /usr/share/texlive/texmf-local/tex/latex/yliowtest')
os.system('cd tmp/update-vm-data/; cp -r latex/*  /usr/share/texlive/texmf-local/tex/latex/yliowtest/')
os.system('cd tmp/update-vm-data/; chmod a+rwx /usr/share/texlive/texmf-local/tex/latex/yliowtest')
os.system('texhash')

# python
for p in ['/usr/lib/python*.*', '/usr/lib64/python*.*']:
    os.system('cd tmp/update-vm-data/; cp -r python/* %s/site-packages/' % p)
    os.system('chmod a+rwx %s/site-packages/' % p)

# alex

os.system('rm -rf tmp')

